learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = "learning_logs"

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Page that shows all the topics
    path('topics/', views.topics, name='topics'),
    # Details page for a specific topic
    path('topic/<int:topic_id>', views.topic, name='topic'),
    # For adding a new topic.
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # Page for editing an entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include the default auth urls.
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """ Creating the Topic Field for the users. """
    topic = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """ Returns the topic with it's name instead of an object. """
        return self.topic


class Entry(models.Model):
    """ Creating the Entries for the specific topic to be logged. """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        length = len(self.text)
        if length > 50:
            show_text =  f"{self.text[:50]}..."
        else:
            show_text = f"{self.text}"
        return show_text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['topic']
        label = {'topic': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Entry
from. forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

def index(request):
    """ The home page for Learning Log. """
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """ Show all topics. """
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {
        'title': 'Learning_Logs/Topics',
        'topics': topics, 
        }
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """ Show a specific data for a topic. """
    # topic = Topic.objects.get(id=topic_id)
    topic = get_object_or_404(Topic, id=topic_id)
    # Restrict the another user to access the data through the url added by the different user.
    if topic.owner != request.user:
        raise Http404
    enrty = topic.entry_set.order_by('-date_added')
    context = {
        'title': topic,
        'topic': topic,
        'entries': enrty,
        }
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """ Add a new topic. """
    if request.method == "POST":
        form = TopicForm(request.POST)
        if form.is_valid():
            # Process the form request and save the data.
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            return redirect("learning_logs:topics")
    else:
        # Create a blank form
        form = TopicForm()
    # Displaying the form
    context = {
        'title': 'Learning_Logs/Topics',
        'form': form,
        }
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """ Add a new entry for a particular topic. """
    topic = Topic.objects.get(id=topic_id)
    if request.method == "POST":
        form = EntryForm(request.POST)
        if form.is_valid():
            # Process the request when user press submit
            new_entry = form.save(commit=False)
            # Assign the new_enrty.topic to topic i.e. for example java to it's content.
            new_entry.topic = topic
            # Saving the foregin key role of the new_entry with the related_name i.e. entry_set.all().
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    else:
        # Create a blank entry form
        form = EntryForm()
    context = {
        'title': 'Learning_Logs/Entries',
        'topic': topic,
        'form': form
        }
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """ Edit an existing entry """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    
    if request.method == 'POST':
        # POST data submitted; process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    else:
        # Returns the Initial Form with the pre-filled data
        form = EntryForm(instance=entry)
    context = {
        'title': f'Learning_Logs/Update/{entry_id}',
        'topic': topic,
        'entry': entry,
        'form': form
    }
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method == "POST":
        # Process the user registration and then login.
        form = UserCreationForm(request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    else:
        # Display a blank registration form for user to handle their requests.
        form = UserCreationForm()
    context = {
        'title': 'Learning_Logs/New_User',
        'form': form
    }
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% if title %} {{ title }} {% else %} Learning_Logs/Home {% endif %}
    </title>
    {% bootstrap_css %}
  </head>
  <body>
    {% block navbar %}
      {% include './includes/nav.html' %}
    {% endblock navbar %}
    <main role="main" class="container" style="padding-top:50px;">
      <div class="{% if not user.is_authenticated %} pb-2 mb-2 border-bottom {% else %} pb-2 mb-2 {% endif %}">
        {% block page_header %} {% endblock page_header%}
      </div>
      <div>
        {% block content %}
      
        {% endblock content %}  
      </div>
    </main>
    
    {% bootstrap_javascript %}

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}
{% block page_header %}
<div class="border-bottom">
    <a class="btn btn-dark btn-lg my-2" href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
</div>
{% endblock page_header %}
{% block content %}
    
    <p class="display-6">Edit entry:</p>
    
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Save Changes" %}
        
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/includes/nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'learning_logs:topics' %}">Topics</a>
          </li>
        </ul>
        <ul class="navbar-nav me-5">
        {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
        {% else %}
            <li class="nav-item mt-2">
                <span class="navbar-text mx-5"> Hello, {{user.username}}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
            </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </nav>

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %} 
{% block page_header %}
<div class="card bg-light border-0" style="height:300px; padding:30px 0;">
  <div class="card-body">
    <h1 class="display-3">Tack your learning.</h5>
    <p class="lead">
      Make your own Learning Log, and keep a list of topics you're learning about. Whenever you
      learn something new about a topic, make an entry summarizing what you've learned.
      </p>
    {% if not user.is_authenticated %}
      <a href="{% url 'users:register' %}" class="mt-3 btn btn-primary btn-lg">Register &raquo;</a>
      {% else %}
        <a href="{% url 'learning_logs:topics' %}" class="mt-3 btn btn-primary btn-lg">Topics &raquo;</a>
    {% endif %}
  </div>
</div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
    <div class="border-bottom">
        <h3 class="display-3">{{ topic }} </h3>
    </div>
{% endblock page_header %}
{% block content %}
    <div class="display-6">Entries:</div>
    <div class="d-flex mb-3 justify-content-center">
        <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-outline-dark">Add a new entry</a>
    </div>
    <div class="row">
        {% for entry in entries %}
            <div class="card m-2
            {% if entry.id|divisibleby:2 == 0 %}
                bg-primary
                text-white
            {% else %}
                bg-danger
                text-white
            {% endif %}
            ">
                <h5 class="card-header">{{ entry.date_added | date:'M d, Y H:i'  }} <span class="badge text-bg-dark"><a class="text-white" href="{% url 'learning_logs:edit_entry' entry.id %}">Edit Entry</a></span></h5>
                <div class="card-body">
                    <p class="card-text">{{ entry.text |linebreaks }}</p>
                </div>
            </div>
            {% empty %}
            <div class="alert alert-info"> No Entries are found for this {{ topic }}!</div>
        {% endfor %}
        </div>
    
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block content %}
    <p class="display-3">Topics</p>
    <div class="row">
    {% for topic in topics %}
    <div class="card m-2 
        {% if topic.id|divisibleby:2 == 0 %}
            bg-primary
            text-white
        {% else %}
            bg-danger
            text-white
        {% endif %}
     " 
    style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ topic }}</h5>
          <a href="{% url 'learning_logs:topic' topic.id %}" 
          class="btn {% if topic.id|divisibleby:2 == 0 %}
            btn-primary text-white
          {% else %}
            btn-danger text-white
          {% endif %}">{{ topic }}</a>
        </div>
      </div>
        {% empty %}
        <div class="alert alert-info">No topics have been added yet.</li>
    {% endfor %}
    </div>
    <div clas="row">
        <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-outline-dark">Add a new topic</a>
    </div>
{% endblock content %}